### ISSUE TITLE
Must remove header presence route rules

### ISSUE THREAD

**Issue by aknot242** [f5devcentral/f5xc-lab-mcn-practical#24]
In Manipulation exercise 1, it states: "Keep your configuration from the previous exercise in place."

If you keep the header route rules in place from the previous exercise, the test will not pass.

**Comment by kreynoldsf5** [comment]
@aknot242,

The test is no longer sending the ``X-MCN-lab`` header. Am I misunderstanding the issue?

**Comment by kreynoldsf5** [comment]
#33 Should address this.
