### ISSUE TITLE
Portability - Create more space between images

### ISSUE THREAD

**Issue by aknot242** [f5devcentral/f5xc-lab-mcn-practical#25]
In the Portability lab's "Why did that work" reveal, the two separate images could use a little separation or ideally a description of what each screenshot is. Without separating the images, it creates the impression that it is a single screenshot (instead of two) which causes confusion.

<img width="919" alt="image" src="https://github.com/f5devcentral/f5xc-lab-mcn-practical/assets/4582399/8cc467d8-cf62-4e41-97a3-086a8aa7cbc0">

**Comment by kreynoldsf5** [comment]
👍

picked this one up in one of the many recent commits.
